version: '3.1'

services:
  mongo:
    image: mongo:4.2
    container_name: springboot-mongo
    volumes:
      - $HOME/data/springboot-mongo-data:/data/db
      - $HOME/data/springboot-mongo-bkp:/data/bkp
    restart: always


  springboot:
    build: .
    restart: always
    container_name: springboot
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
      - mongo


